### ISSUE TITLE
Pig/Not Pig algorithm

### ISSUE THREAD

**Issue by Nova-Scotia** [mikeyEcology/MLWIC#33]
Hi Mikey,

In the bioRxiv version of your paper, I read about your "Pig/no pig" model. We're interested in testing that model - are you able to share that one?

**Comment by mikeyEcology** [comment]
Hi Erica,
I might be able to dig up that model and make it available. I have a couple of questions though: Are you planning on using this to ID empty images specifically (ie. determine if a picture is animal/ no animal) or are you workin on images with pigs? What kind of timeline are you working with?
I ask because I'm currently training a model to detect animals in images that I think will be pretty effective because we have training data from a lot of locations. This will be available in the next version of MLWIC, but it is taking a long time to train and is about 2 months away from completion. 
Mikey

**Comment by Nova-Scotia** [comment]
Hi Mikey,

Thanks for the quick reply! We're curious about how well the model does
with specifically "pig" or "no pig" (versus "animal" vs "no animal"). The
earliest we would need it would likely be mid January, but perhaps as late
as early February. The new algorithm sounds exciting - we will be keen to
try it out! Shall I touch base with you in January and see where you are at
(here or via email better)?

**Comment by mikeyEcology** [comment]
For anyone reading this issue in the future, we switched to email for discussion, but I am making this trained model available by request, so please comment on this issue if you would like to use this model.

**Comment by Nova-Scotia** [comment]
Hi again Mikey,

I've finally got my test images ready to go to try out the Pig/No Pig model. I've got everything working with these images when I test using `MLWIC` and the 26-species model. But I'm really having trouble with the Pig/No Pig model. The classify code seems to expect the main folder to be called "L1" no matter what I specify, so I've named the "Pig/No pig" model folder you provided "L1", since otherwise the function keeps dropping files into that folder anyway. I've used the "USDA50.log" file to guide me in choosing appropriate parameters for the classify call. I've taken some screenshots to show you the folder hierarchy so we can ensure I've got stuff in the right place:

![image](https://user-images.githubusercontent.com/38108750/107229880-5b4e7980-69ec-11eb-8771-59887e7e5c5c.png)

inside architectures:

![image](https://user-images.githubusercontent.com/38108750/107229917-66090e80-69ec-11eb-8bc7-d81ec892cf17.png)

Here's the code and my error message (it does not produce the indicated predictions file):

<pre>
<b>classify(</b> 
  
  <i># this is the absolute path to the images containing wildlife to classify.
  # No images should have more than one species, but there can be more than one individual of the same species.
  # There should be NO subdirectories in the "images" folder.</i>
  <b>path_prefix = "C:/Users/NewtonEr/MyFiles/Management/IMF/CameraTraps/TestMLWIC/Pig_pics_twocams",  </b> 
  
  <i># this is the location of the .csv containing image information. It has Unix linebreaks and no headers.
  # The first column contains the file name of the jpg image e.g., "CA-01_0006501.jpg"
  # The second column MUST contain the NUMBER corresponding to the species in the image, e.g., 25 - this can be used to check the accuracy of the classification. DO NOT LEAVE IT BLANK OR IT WILL NOT WORK.
  # This file MUST be named data_info.csv and it MUST be located in the L1 folder.</i>
  <b>data_info = "C:/Users/NewtonEr/MyFiles/Management/IMF/CameraTraps/TestMLWIC/L1/data_info.csv", </b> 
  
  <i># This is where you stored the L1 folder in Step 3 of the instructions at: 
  # github.com/mikeyEcology/MLWIC/blob/master/README</i>
  <b>model_dir = "C:/Users/NewtonEr/MyFiles/Management/IMF/CameraTraps/TestMLWIC", </b> 
  
  <i># the location of Python on your computer. 
  # NOTE you MUST have a slash ("/") at the end of the path!!!</i>
  <b>python_loc = "C:/Users/NewtonEr/Anaconda/", </b> 
  
  <b>os = "Windows",</b> 
  
  <b>log_dir = "USDA50",</b> 
  
  <b>depth = "50",</b>  <i># I've tried quoted and unquoted, and numbers 8, 18, 50</i>

 <b> num_classes = 2,</b> 

  <b>top_n = "2", </b> <i># I've tried quoted and unquoted</i>
  
  <i># Model_predictions.txt is the default, and you should use it unless you have reason otherwise.</i>
  <b>save_predictions = "model_predictions_pigs_PigNoPigModel_2021.txt"</b> 
)

Traceback (most recent call last):
  File "eval.py", line 15, in <module>
    import arch
  File "C:\Users\NewtonEr\MyFiles\Management\IMF\CameraTraps\TestMLWIC\L1\arch.py", line 1, in <module>
    import architectures.alexnet
  File "C:\Users\NewtonEr\MyFiles\Management\IMF\CameraTraps\TestMLWIC\L1\architectures\alexnet.py", line 2, in <module>
    import common
ModuleNotFoundError: No module named 'common'
[1] "evaluation of images took 3.53698897361755 secs. The results are stored in C:/Users/NewtonEr/MyFiles/Management/IMF/CameraTraps/TestMLWIC/L1/model_predictions_pigs_PigNoPigModel_2021.txt. To view the results in a viewer-friendly format, please use the function make_output"
</pre>
